# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cert
    sigh
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner"      
    )
    #testfairy(
    #  api_key: "0f220c37a34c643be3179cdbd1b27bf11ff8330e",
    #  ipa: "../Runner.ipa",
    #  comment: "Build #{lane_context[SharedValues::BUILD_NUMBER]}",
    #)
    upload_to_testflight
  end
end